#Server Config
server:
  port: 8181
#Files
spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  #jackson
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  #Data type configuration
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  #Datasource
  datasource:
    url: deveSerPassadoViaVMOptions
    username: deveSerPassadoViaVMOptions
    password: deveSerPassadoViaVMOptions
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type: trace
        default_schema: nfe_reader
cloud:
  aws:
    region: us-east-1