#Server Config
server:
  port: 8181
#Files
spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  #jackson
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  #Data type configuration
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  #Datasource
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type: trace
        default_schema: nfe_reader

aws:
  config:
    region: us-east-1
    bucketName: nfe-reader-xml190442-nfereader
    sqsXml: nfeReaderQueue
    sqsZip: nfeReaderQueueZip