region      = "us-east-1"
app_name    = "nfe-reader-processor-app"
env_name    = "nfe-reader-processor-env"
bucket_name = "nfe-reader-processor-bucket"
xml_bucket_name = "nfe-reader-xml190442-nfereader"
